[centos]
centos01 ansible_host=10.0.2.9
centos02 ansible_host=10.0.2.6

[ubuntu]
ubuntu01 ansible_host=10.0.2.10
ubuntu02 ansible_host=10.0.2.110

[linux:children]
centos
ubuntu

[database]
ubuntu-db ansible_host=10.0.2.10
